modLoader="javafml"
loaderVersion="[2,)"
issueTrackerURL="https://github.com/Mrbysco/ageing-mobs/issues"
license="MIT"

[[mods]]
modId="ageingmobs"
version="${file.jarVersion}"
displayName="Ageing Mobs Mod"
displayURL="https://www.curseforge.com/minecraft/mc-mods/ageing-mobs"
logoFile="logo.png"
authors="ShyNieke, Mrbysco"
credits="Plutosion for testing"
description='''
This mod allows mobs to age and transform.
'''
[[dependencies.ageingmobs]]
modId="minecraft"
type="REQUIRED"
versionRange="[1.20.4,1.21)"
ordering="NONE"
side="BOTH"