modLoader="javafml"
loaderVersion="[4,)"
issueTrackerURL="https://github.com/Mrbysco/ageing-mobs/issues"
license="MIT"

[[mods]]
modId="ageingmobs"
version="${file.jarVersion}"
displayName="Ageing Mobs Mod"
displayURL="https://www.curseforge.com/minecraft/mc-mods/ageing-mobs"
iconFile="logo.png"
authors="ShyNieke, Mrbysco"
credits="Plutosion for testing"
description='''
This mod allows mobs to age and transform.
'''
[[dependencies.ageingmobs]]
modId="minecraft"
type="required"
versionRange="[26.2,)"
ordering="NONE"
side="BOTH"
[[dependencies.ageingmobs]]
modId="neoforge"
type="required"
versionRange="[26.2.0.0-alpha,)"
ordering="NONE"
side="BOTH"